using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace AccountManagementSystem.Data
{
	public interface IRepository<T>
	{
		Task<IEnumerable<T>> GetAllAsync();
		Task DeleteRowAsync(int id);
		Task<T> GetAsync(int id, string primaryKeyName);
		Task UpdateAsync(T entity);
		Task<int> InsertAsync(T entity, string nameOfAutoGeneratedKey = null);
	}
}
