using AccountManagementSystem.Data;
using AccountManagementSystem.Model;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace AccountManagementSystem.Service
{
	public class PersonRepository
	{
		private readonly IRepository<Person> _personRepository;
		private const string _tableName = "Persons";
		private const string _connectionString = "Server=(localdb)\\MSSQLLocalDB;Integrated Security=true;Initial Catalog=AMSContext";
		private const string _primaryKeyName = "code";
		public PersonRepository()
		{
			_personRepository = new Repository<Person>(_tableName, _connectionString);
		}

		public async Task<IEnumerable<Person>> GetAllPeopleAsync()
		{
			return await _personRepository.GetAllAsync();
		}

		public async Task<Person> GetPerson(int code)
		{
			return await _personRepository.GetAsync(code, _primaryKeyName);
		}

		public async Task AddPersonAsync(Person person, string autoGeneratedKeyName)
		{
			await _personRepository.InsertAsync(person, autoGeneratedKeyName);
		}
	}
}
